name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0
        continue-on-error: true

      - name: Ensure gh-pages branch exists (create if missing)
        shell: bash
        run: |
          set -euxo pipefail
          rm -rf gh-pages
          git clone --depth 1 --branch gh-pages "${{ github.server_url }}/${{ github.repository }}.git" gh-pages || true
          if [ ! -d gh-pages/.git ]; then
            mkdir -p gh-pages
            cd gh-pages
            git init
            git remote add origin "${{ github.server_url }}/${{ github.repository }}.git"
            git checkout -b gh-pages
            touch .nojekyll
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .nojekyll
            git commit -m "chore: initialize gh-pages branch"
            git push -u origin gh-pages
          fi

      - name: Checkout main (for production site)
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v4
        with:
          ref: main
          path: repo
          fetch-depth: 0

      - name: Sync production site into gh-pages (preserve dev previews)
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          set -euxo pipefail
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rsync -a --delete --exclude '.git' --exclude 'dev/' --exclude '.nojekyll' --exclude 'CNAME' ../repo/ .
          touch .nojekyll
          if git status --porcelain | grep .; then
            git add -A
            git commit -m "chore: sync production site from main"
            git push origin HEAD:gh-pages
          else
            echo "No changes to commit to gh-pages."
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (gh-pages content)
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4