name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update cache version
        run: |
          # Get current cache version from service-worker.js
          CURRENT_VERSION=$(grep -oP "const CACHE_NAME = 'botc-party-grimoire-v\K[0-9]+" service-worker.js)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          
          # Update the cache version in service-worker.js
          sed -i "s/const CACHE_NAME = 'botc-party-grimoire-v${CURRENT_VERSION}'/const CACHE_NAME = 'botc-party-grimoire-v${NEW_VERSION}'/" service-worker.js
          
          echo "Updated cache version from v${CURRENT_VERSION} to v${NEW_VERSION}"
          
          # Show the change
          grep "const CACHE_NAME" service-worker.js

      - name: Commit cache version bump
        run: |
          if git diff --quiet service-worker.js; then
            echo "No cache version change to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add service-worker.js
            git commit -m "chore: bump service worker cache [skip ci]"
            git push
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4