name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update cache version
        run: |
          # Get current cache version from service-worker.js
          CURRENT_VERSION=$(grep -oP "const CACHE_NAME = 'botc-offline-grimoire-v\K[0-9]+" service-worker.js)
          NEW_VERSION=$((CURRENT_VERSION + 1))
          
          # Update the cache version in service-worker.js
          sed -i "s/const CACHE_NAME = 'botc-offline-grimoire-v${CURRENT_VERSION}'/const CACHE_NAME = 'botc-offline-grimoire-v${NEW_VERSION}'/" service-worker.js
          
          echo "Updated cache version from v${CURRENT_VERSION} to v${NEW_VERSION}"
          
          # Show the change
          grep "const CACHE_NAME" service-worker.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4